python finetune_yoloworld_scratch.py \
  --model-size s \
  --yolo-train data/yoloworld_v3/data.yaml \
  --yolo-val data/yoloworld_v3/data.yaml \
  --grounding "flickr30k/images:flickr30k/final_flickr_separateGT_train.json" \
  --grounding "GQA/images:GQA/final_mixed_train_no_coco.json" \
  --epochs 50 --batch-size 64 --img-size 640 --device 0 \
  --project runs/world_from_scratch --name exp_scratch_v1 \
  --single-cls \
  --mosaic 1.0 --close-mosaic 10 --mixup 0.2 \
  --copy-paste 0.2 --erasing 0.4 \
  --flipud 0.0 --fliplr 0.5 \
  --degrees 0.0 --translate 0.1 --scale 0.5 --shear 0.0 --perspective 0.0 \
  --hsv-h 0.015 --hsv-s 0.7 --hsv-v 0.4